pipeline:
  build:
    image: centos:7
    commands:
      - yum install -y epel-release
      - yum group install -y "Development Tools" 
      - yum install -y mysql-devel gmp-devel python-devel python-pip
      - pip install --upgrade pip
      - pip install pex
      - pex salt mysql-python python-gnupg -c salt-master -o salt-master.pex
      - pex salt mysql-python python-gnupg -c salt-minion -o salt-minion.pex
      - pex salt mysql-python python-gnupg -c salt-api -o salt-api.pex
      - pex salt mysql-python python-gnupg -c salt-call -o salt-call.pex
      - pex salt mysql-python python-gnupg -c salt -o salt.pex
      - pex salt mysql-python python-gnupg -c salt-key -o salt-key.pex
      - pex salt mysql-python python-gnupg -c salt-ssh -o salt-ssh.pex
      - ./salt-minion.pex --version

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: "*.pex"
    checksum:
      - sha256
    when:
      event: tag
