pipeline:
  build-pex:
    image: centos:7
    commands:
      - yum install -y epel-release
      - yum group install -y "Development Tools" 
      - yum install -y libssh2 python-pygit2 mysql-devel gmp-devel python-devel python-pip
      - pip install --upgrade pip
      - pip install pex
      - pex salt mysql-python python-gnupg -c salt-run -o salt-run
      - pex salt mysql-python python-gnupg -c salt-master -o salt-master
      - pex salt mysql-python python-gnupg -c salt-minion -o salt-minion
      - pex salt mysql-python python-gnupg -c salt-api -o salt-api
      - pex salt mysql-python python-gnupg -c salt-call -o salt-call
      - pex salt mysql-python python-gnupg -c salt -o salt
      - pex salt mysql-python python-gnupg -c salt-key -o salt-key
      - pex salt mysql-python python-gnupg -c salt-ssh -o salt-ssh
      - ./salt-minion --version
    when:
      event: tag

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: "salt*"
    checksum:
      - sha256
    when:
      event: tag

  build-and-push-docker:
    image: plugins/docker
    repo: fpfis/salt-pex
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    auto_tag: true
    when:
      event: [ push, tag ]
      branch: master

  build-and-push-private-docker:
    image: plugins/docker
    repo: registry.fpfis.tech.ec.europa.eu/salt-pex
    registry: registry.fpfis.tech.ec.europa.eu
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    auto_tag: true
    when:
      event: [ push, tag ]
      branch: master
