pipeline:
  build:
    image: centos:7
    commands:
      - yum install -y epel-release
      - yum group install -y "Development Tools" 
      - yum install -y python-pip
      - pip install pex
      - pex salt -c salt-master -o build/salt-master.pex
      - pex salt -c salt-minion -o build/salt-minion.pex
      - pex salt -c salt-api -o build/salt-api.pex
      - ls -lha build/
