pipeline:
  build:
    image: centos:7
    commands:
      - yum install -y epel-release
      - yum group install -y "Development Tools" 
      - yum install -y gmp-devel python-devel python-pip
      - pip install --upgrade pip
      - pip install pex
      - pex salt -c salt-master -o salt-master.pex
      - pex salt -c salt-minion -o salt-minion.pex
      - pex salt -c salt-api -o salt-api.pex
